app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controllers([
	'auth'		=> 'Auth\AuthController',
	'password'	=> 'Auth\PasswordController',
	
]);

Route::group([ 'middleware' => 'auth'], function(){

//--------------------RUTAS SECRETARIA------------------------------------------
	Route::get('/','HomeController@index');
	Route::get('/auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
	Route::resource('usuario','usercontroller');
	Route::resource('tipo-evento','TipoEventoController');
	Route::resource('evento','EventoController');
	Route::resource('vinculacion','VinculacionController');
	Route::resource('programa','ProgramaController');
	Route::resource('nivel-estudio','NivelEstudioController');
	Route::resource('profesores','ProfesorController');
	Route::resource('planes-estudio','PlanEstudioController');
	Route::resource('cursos','CursoController');
	Route::resource('titulacion-docente','TitulacionController');
	Route::resource('evaluacion-docente','EvaluacionDocenteController');
	Route::resource('responsabilidad-docente','ResponsabilidadDocenteController');
	Route::post('responsabilidad-docente/importar','ResponsabilidadDocenteController@importar');
	Route::get('descargar_formato/{formato}','ResponsabilidadDocenteController@descargarFormato');
	Route::resource('dedicacion-docente','DedicacionDocenteController');
	Route::resource('permisos-secretaria','PermisosSecretariaController');
	Route::resource('secretaria-estudiante','EstudiantesPreuController');
	Route::resource('movilidad-docente','MovilidadController');
	Route::resource('funciones-administrativas','FuncionAdministrativaController');
	Route::resource('actividades','ActividadesController');
	route::get('/home','HomeController@home');
	Route::get('grafica/{id}','GraficasSecretariaController@grafJason');
	Route::get('grafica','GraficasSecretariaController@grafica');
//-------------------RUTAS PROGRAMA------------------------------------------
	Route::resource('estudiante','estudianteController');
    Route::get("json/usuario","datatablesController@getUsuarios");
    Route::get("preguntas","preguntasController@index");
    Route::post("preguntas/create","preguntasController@create");
    Route::post("preguntas/store","preguntasController@store");
    Route::resource('encuesta','encuestaController');
    Route::resource('grupo','grupoController');
    Route::resource('practicas','practicasController');
    Route::get('practicas/estudiantes/{id}','practicasController@estudiantes');
    Route::post('practicas/estudiantes/{id}','practicasController@estudiantesStore');
    Route::get('practicas/evaluar/{id}','practicasController@evaluar');
    Route::post('practicas/evaluar/{id}','practicasController@evaluarEstudiante');
    Route::post('practicas/evaluar/{id}/{estudiante}','practicasController@evaluarStore');
    Route::resource('inscripcion','InscripcionEstudianteCursoController');
    Route::resource('periodo','periodoController');
    Route::resource('rotacion','rotacionController');
    Route::resource('homologacion','homologacionController');
    Route::get('ajax/cargarRotaciones','ajaxController@cargarRotaciones');
    Route::get('graficas','graficasController@index');
    Route::get('graficar','graficasController@graficar');
});

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

resources/views/usuario/create.blade.php
@extends('layaouts.tablas')
@section('content')
  <section class="content">
    <div class="row">
      <div class="col-md-9">
      @include('errors.partials.requesterror')
        <div class="box box-solid box-danger">
          <div class="box-header with-border">
            <h1 class="box-title">Agregar Usuario</h1>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="pad">
                {!! Form::open($route) !!}
                @include('usuario.partials.form')    
                {!!Form::close()!!}    
              </div>
            </div><!-- /.row pad-->
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div><!--/.row-->
  </section><!-- /.content -->
@endsection

resources/views/usuario/edit.blade.php
@extends('layaouts.tablas')
@section('content')
  <section class="content">
    <div class="row">
      <div class="col-md-9">
      @include('errors.partials.requesterror')
        <div class="box box-solid box-danger">
          <div class="box-header with-border">
            <h3 class="box-title">Editar Usuario</h3>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="pad">
                {!!Form::model($usuario,['route'=>['usuario.update',$usuario->id],'method'=>'PUT'])!!}
                @include('usuario.partials.edit')       
                {!!Form::close()!!}                                    
              </div>
            </div><!-- /.row pad-->
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>
  </section><!-- /.content --> 
@endsection

resources/views/usuario/index.blade.php
@extends('layaouts.tablas')
@section('content')
  <section class="content">
    @include('usuario.partials.modal') 
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            @include('layaouts.partials.mensaje')
            <h3 class="box-title">Listado de Usuarios</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="row form-group">
              <div class="col-md-3">
                <a href="{!! URL('usuario/create') !!}" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo Usuario</a>
              </div>
            </div>
            <table id="example3" class="table table-bordered table-striped">
              <thead>
                <th>Usuario</th>
                <th>Email</th>
                <th>Dependencia</th>
                <th>Acción</th>
              </thead>
              <tbody>
                @foreach($usuarios as $user)
                  <tr>
                    <td>{{ $user->name}}</td>
                    <td>{{ $user->email}}</td>
                    <td>{{ $user->dependencia}}</td>
                    <td>
                      {!! link_to_route('usuario.edit', $title='Editar', $parameters=$user->id, $atrributes=['class'=>'btn btn-warning']) !!}
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>   
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div><!-- /.col -->
    </div>                   
  </section><!-- /.content -->
@endsection