app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controllers([
	'auth'		=> 'Auth\AuthController',
	'password'	=> 'Auth\PasswordController',
	
]);

Route::group([ 'middleware' => 'auth'], function(){

//--------------------RUTAS SECRETARIA------------------------------------------
	Route::get('/','HomeController@index');
	Route::get('/auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
	Route::resource('usuario','usercontroller');
	Route::resource('tipo-evento','TipoEventoController');
	Route::resource('evento','EventoController');
	Route::resource('vinculacion','VinculacionController');
	Route::resource('programa','ProgramaController');
	Route::resource('nivel-estudio','NivelEstudioController');
	Route::resource('profesores','ProfesorController');
	Route::resource('planes-estudio','PlanEstudioController');
	Route::resource('cursos','CursoController');
	Route::resource('titulacion-docente','TitulacionController');
	Route::resource('evaluacion-docente','EvaluacionDocenteController');
	Route::resource('responsabilidad-docente','ResponsabilidadDocenteController');
	Route::post('responsabilidad-docente/importar','ResponsabilidadDocenteController@importar');
	Route::get('descargar_formato/{formato}','ResponsabilidadDocenteController@descargarFormato');
	Route::resource('dedicacion-docente','DedicacionDocenteController');
	Route::resource('permisos-secretaria','PermisosSecretariaController');
	Route::resource('secretaria-estudiante','EstudiantesPreuController');
	Route::resource('movilidad-docente','MovilidadController');
	Route::resource('funciones-administrativas','FuncionAdministrativaController');
	Route::resource('actividades','ActividadesController');
	route::get('/home','HomeController@home');
	Route::get('grafica/{id}','GraficasSecretariaController@grafJason');
	Route::get('grafica','GraficasSecretariaController@grafica');
//-------------------RUTAS PROGRAMA------------------------------------------
	Route::resource('estudiante','estudianteController');
    Route::get("json/usuario","datatablesController@getUsuarios");
    Route::get("preguntas","preguntasController@index");
    Route::post("preguntas/create","preguntasController@create");
    Route::post("preguntas/store","preguntasController@store");
    Route::resource('encuesta','encuestaController');
    Route::resource('grupo','grupoController');
    Route::resource('practicas','practicasController');
    Route::get('practicas/estudiantes/{id}','practicasController@estudiantes');
    Route::post('practicas/estudiantes/{id}','practicasController@estudiantesStore');
    Route::get('practicas/evaluar/{id}','practicasController@evaluar');
    Route::post('practicas/evaluar/{id}','practicasController@evaluarEstudiante');
    Route::post('practicas/evaluar/{id}/{estudiante}','practicasController@evaluarStore');
    Route::resource('inscripcion','InscripcionEstudianteCursoController');
    Route::resource('periodo','periodoController');
    Route::resource('rotacion','rotacionController');
    Route::resource('homologacion','homologacionController');
    Route::get('ajax/cargarRotaciones','ajaxController@cargarRotaciones');
    Route::get('graficas','graficasController@index');
    Route::get('graficar','graficasController@graficar');
});

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

app/Curso.php
<?php

namespace FCS;

use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    protected $table = 'cursos';
    protected $fillable=['codigo_curso','nombre_curso','tipo_curso','semestre','area','creditos','id_planestudio'];

    public function plan()
    {
    	return $this->belongsTo('\FCS\PlanEstudio','id_planestudio');
    }   
}

app/Http/Controllers/CursoController.php
<?php
namespace FCS\Http\Controllers;

use Illuminate\Http\Request;

use FCS\Curso;
use FCS\PlanEstudio;

use FCS\Http\Requests;
use FCS\Http\Controllers\Controller;
use FCS\Http\Requests\Cursos\CreateRequest;
use FCS\Http\Requests\Cursos\UpdateRequest;

use DB, View, Session, Redirect;

class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");

        $cursos=Curso::All();
        return view('componentes.cursos.index',compact('cursos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");

        $planes = PlanEstudio::ListaPlanes();
        $route = [ 'route' => 'cursos.store' ];
        return view('componentes.cursos.addcurso',compact('planes','route'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(CreateRequest $request)
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");

        Curso::create($request->all());
        return redirect('cursos')->with('message','Curso Creado Exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");

        $planes = PlanEstudio::ListaPlanes();
        $cursos=Curso::find($id);
        $route = [ 'route'=>['cursos.update',$cursos->id],'method'=>'PUT'];
        return view('componentes.cursos.editcurso', compact('planes','route','cursos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(UpdateRequest $request, $id)
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");

        $planes = PlanEstudio::ListaPlanes();
        $cursos=Curso::find($id);
        $cursos->fill($request->all());
        $cursos->save();

        Session::flash('message','Curso Editado Correctamente');
        return redirect::to('cursos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        if(!\FCS\Permiso::verificarPermiso("cursos"))
        return redirect("/");
    
        Curso::destroy($id);
        Session::flash('message','Curso Eliminado Correctamente');
        return Redirect::to('/cursos');
    }

}

resources/views/formulario programa/Secretaria/Curso/Inscripcion_EstuCurso.blade.php
@extends('layaouts.newtablas')    
@section('content')
<section class="content">
  <div class="row"> 
    <div class="col-md-12">
      <div class="box">
        <div class="box-header" data-original-title>
          <h2><i class="fa fa-user-plus"></i><span class="break"></span><b>Inscripción Estudiante al Curso</b></h2>
          <div class="box-icon">
            <a href="#" class="btn-minimize"><i class="fa fa-chevron-up"></i></a>
          </div>
        </div>
        <div class="box-content"> 
          {!! Form::open($route) !!}
            <div class="row form-group">
              <div class="col-md-12">
                {!! Form::label('Estudiante')!!}
                {!!Form::select("id_estudiante",$estudiantes,$inscripcion->id_estudiante,["class"=>"form-control","data-rel"=>"chosen"])!!}
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                {!! Form::label('Grupo')!!}
                {!!Form::select("id_grupo",$grupos,$inscripcion->id_grupo,["class"=>"form-control","data-rel"=>"chosen"])!!}
              </div>
            </div>
            <div class="row form-group">
              <div class="col-md-12">
                {!!Form::submit('Guardar',['class'=>'btn btn-success'])!!}
              </div>     
            </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/formulario programa/Secretaria/Curso/index.blade.php
@extends('layaouts.newtablas')

   @if(Session::has('message'))
      <div class="alert alert-danger alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         {{ Session::get('message')}}
      </div>
   @endif
@section('content')
   <section class="content">  
   @if(\Session::get("mensaje"))
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {!! \Session::get("mensaje") !!}
    </div>
  @endif
  @if(\Session::get("mensaje-error"))
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {!! \Session::get("mensaje-error") !!}
    </div>
  @endif
  @foreach($inscripciones as $i) 
    <div class="modal fade" id="modalBorrar{!! $i->id !!}">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Eliminar Registro</h4>
            </div>
            <div class="modal-body">
              <p>Esta seguro de eliminar el registro seleccionado?</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(array("route"=>array("inscripcion.destroy",$i->id),"method"=>"DELETE")) !!}
                <button type="submit" class="btn btn-success">Si</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
              {!! Form::close() !!}
            </div>
          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
  @endforeach
      <div class="row">
            <div class="col-xs-12">
              <div class="box">
               <div class="box-header">
                  <h2 class="box-title"><i class="fa fa-user-plus"></i><b>Listado de Inscripciones</b></h2>
               </div><!-- /.box-header -->
               <div class="box-body">
                  <div class="row form-group">
                    <div class="col-md-3">
                      <a href="{!! URL('inscripcion/create') !!}" class="btn btn-success"><i class="fa fa-plus"></i> Crear una nueva inscripción</a>
                    </div>
                  </div>
                   <table id="example3" class="table table-bordered table-striped">
                     <thead>
                        <th>Estudiante</th>
                        <th>Grupo</th>
                        <th>Acción</th>
                     </thead>
                     <tbody>
                        @foreach($inscripciones as $i)     
                          <tr>       
                            <td>{{ $i->codigo_estudiante." ".$i->primer_nombre." ".$i->segundo_nombre." ".$i->apellido_paterno." ".$i->apellido_materno}}</td>
                            <td>{{ $i->nombre_curso." ".$i->codigo}}</td>
                            <td>
                               {!! link_to_route('inscripcion.edit', $title='Editar', $parameters=$i->id, $atrributes=['class'=>'btn btn-warning']) !!}
                                <button type="button" class="btn btn-danger" onclick="$('#modalBorrar{!! $i->id !!}').modal();">Borrar</button>
                            </td>
                          </tr>                
                        @endforeach
                      </tbody>
                  </table>   
               </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
      </div>                  

   
  </section><!-- /.content -->
   
@endsection
@section("js-adicional")
    <!-- DATA TABES SCRIPT-->
   {!!Html::script('assets/plugins/datatables/jquery.dataTables.min.js')!!}
   {!!Html::script('assets/plugins/datatables/dataTables.bootstrap.min.js')!!}
   <script type="text/javascript">
       $(function () {
           $('#example3').DataTable({
               language: {
                   lengthMenu:        "Mostrar _MENU_ Registros por Pagina",
                   search:            "Buscar ",
                   searchPlaceholder: "Busca por columnas",
                   info:              "Mostrar _START_ A _END_ De _TOTAL_ Registros",
                   zeroRecords:       "Ningun Registro Encontrado",
                   infoEmpty:         "No Hay Registros Disponibles",
                   paginate: {
                       first:         "Primero",
                       previous:      "<< Anterior",
                       next:          "Siguiente >>",
                       last:          "Ultimo"
                   }
               }
           });
       });
   </script>
@stop