app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controllers([
	'auth'		=> 'Auth\AuthController',
	'password'	=> 'Auth\PasswordController',
	
]);

Route::group([ 'middleware' => 'auth'], function(){

//--------------------RUTAS SECRETARIA------------------------------------------
	Route::get('/','HomeController@index');
	Route::get('/auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
	Route::resource('usuario','usercontroller');
	Route::resource('tipo-evento','TipoEventoController');
	Route::resource('evento','EventoController');
	Route::resource('vinculacion','VinculacionController');
	Route::resource('programa','ProgramaController');
	Route::resource('nivel-estudio','NivelEstudioController');
	Route::resource('profesores','ProfesorController');
	Route::resource('planes-estudio','PlanEstudioController');
	Route::resource('cursos','CursoController');
	Route::resource('titulacion-docente','TitulacionController');
	Route::resource('evaluacion-docente','EvaluacionDocenteController');
	Route::resource('responsabilidad-docente','ResponsabilidadDocenteController');
	Route::post('responsabilidad-docente/importar','ResponsabilidadDocenteController@importar');
	Route::get('descargar_formato/{formato}','ResponsabilidadDocenteController@descargarFormato');
	Route::resource('dedicacion-docente','DedicacionDocenteController');
	Route::resource('permisos-secretaria','PermisosSecretariaController');
	Route::resource('secretaria-estudiante','EstudiantesPreuController');
	Route::resource('movilidad-docente','MovilidadController');
	Route::resource('funciones-administrativas','FuncionAdministrativaController');
	Route::resource('actividades','ActividadesController');
	route::get('/home','HomeController@home');
	Route::get('grafica/{id}','GraficasSecretariaController@grafJason');
	Route::get('grafica','GraficasSecretariaController@grafica');
//-------------------RUTAS PROGRAMA------------------------------------------
	Route::resource('estudiante','estudianteController');
    Route::get("json/usuario","datatablesController@getUsuarios");
    Route::get("preguntas","preguntasController@index");
    Route::post("preguntas/create","preguntasController@create");
    Route::post("preguntas/store","preguntasController@store");
    Route::resource('encuesta','encuestaController');
    Route::resource('grupo','grupoController');
    Route::resource('practicas','practicasController');
    Route::get('practicas/estudiantes/{id}','practicasController@estudiantes');
    Route::post('practicas/estudiantes/{id}','practicasController@estudiantesStore');
    Route::get('practicas/evaluar/{id}','practicasController@evaluar');
    Route::post('practicas/evaluar/{id}','practicasController@evaluarEstudiante');
    Route::post('practicas/evaluar/{id}/{estudiante}','practicasController@evaluarStore');
    Route::resource('inscripcion','InscripcionEstudianteCursoController');
    Route::resource('periodo','periodoController');
    Route::resource('rotacion','rotacionController');
    Route::resource('homologacion','homologacionController');
    Route::get('ajax/cargarRotaciones','ajaxController@cargarRotaciones');
    Route::get('graficas','graficasController@index');
    Route::get('graficar','graficasController@graficar');
});

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

app/Permiso.php
<?php

namespace FCS;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Auth;


class Permiso extends Model
{
    protected $table = 'permisos';
    protected $fillable=['iduser','idmenus','permiso'];

    public static function verificarPermiso($ruta){
        $menu=Menu::where("ruta","=",DB::raw("'".$ruta."'"))->first();
        $permiso=self::where("idmenus","=",DB::raw($menu->id))->where("iduser","=",DB::raw(Auth::user()->id))->first();
        if(!is_null($permiso))
            if($permiso->permiso==1)
                return true;
        return false;
    }

}

resources/views/componentes/permisos/index.blade.php
@extends('layaouts.tablas')
@section('content')
  <section class="content"> 
    @include('componentes.cursos.partials.modal')  
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            @include('layaouts.partials.mensaje')
            <h3 class="box-title">Listado Cursos</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="row form-group">
              <div class="col-md-3">
                <a href="{!! URL('cursos/create') !!}" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo Curso</a>
              </div>
            </div>
            <table id="example3" class="table table-bordered table-striped">
              <thead>
                <th>Codigo Del Curso</th>
                <th>Nombre Del Curso</th>
                <th>Tipo Curso</th>
                <th>Semestre</th>
                <th>Area</th>
                <th>Creditos</th>
                <th>Plan De Estudio</th>
                <th>Acciones</th>
              </thead>
              <tbody>
                @foreach($cursos as $t)
                  <tr> 
                    <td>{{ $t->codigo_curso}}</td>
                    <td>{{ $t->nombre_curso}}</td>
                    <td>{{ $t->tipo_curso}}</td>
                    <td>{{ $t->semestre}}</td>
                    <td>{{ $t->area}}</td>
                    <td>{{ $t->creditos}}</td>
                    <td>{{ $t->plan->codigo}}</td>
                    <td>
                      {!! link_to_route('cursos.edit', $title='Editar', $parameters=$t->id, $atrributes=['class'=>'btn btn-warning']) !!}
                      <button type="button" class="btn btn-danger" onclick="$('#modalBorrar{!! $t->id !!}').modal();">Borrar</button>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
            <div class="row">
              <div class="col-xs-12"><center>PS= Profesional PZ= Profundización</center></div>
            </div>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div><!-- /.col -->
    </div><!-- /.row -->                
  </section><!-- /.content -->
@endsection