app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controllers([
	'auth'		=> 'Auth\AuthController',
	'password'	=> 'Auth\PasswordController',
	
]);

Route::group([ 'middleware' => 'auth'], function(){

//--------------------RUTAS SECRETARIA------------------------------------------
	Route::get('/','HomeController@index');
	Route::get('/auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);
	Route::resource('usuario','usercontroller');
	Route::resource('tipo-evento','TipoEventoController');
	Route::resource('evento','EventoController');
	Route::resource('vinculacion','VinculacionController');
	Route::resource('programa','ProgramaController');
	Route::resource('nivel-estudio','NivelEstudioController');
	Route::resource('profesores','ProfesorController');
	Route::resource('planes-estudio','PlanEstudioController');
	Route::resource('cursos','CursoController');
	Route::resource('titulacion-docente','TitulacionController');
	Route::resource('evaluacion-docente','EvaluacionDocenteController');
	Route::resource('responsabilidad-docente','ResponsabilidadDocenteController');
	Route::post('responsabilidad-docente/importar','ResponsabilidadDocenteController@importar');
	Route::get('descargar_formato/{formato}','ResponsabilidadDocenteController@descargarFormato');
	Route::resource('dedicacion-docente','DedicacionDocenteController');
	Route::resource('permisos-secretaria','PermisosSecretariaController');
	Route::resource('secretaria-estudiante','EstudiantesPreuController');
	Route::resource('movilidad-docente','MovilidadController');
	Route::resource('funciones-administrativas','FuncionAdministrativaController');
	Route::resource('actividades','ActividadesController');
	route::get('/home','HomeController@home');
	Route::get('grafica/{id}','GraficasSecretariaController@grafJason');
	Route::get('grafica','GraficasSecretariaController@grafica');
//-------------------RUTAS PROGRAMA------------------------------------------
	Route::resource('estudiante','estudianteController');
    Route::get("json/usuario","datatablesController@getUsuarios");
    Route::get("preguntas","preguntasController@index");
    Route::post("preguntas/create","preguntasController@create");
    Route::post("preguntas/store","preguntasController@store");
    Route::resource('encuesta','encuestaController');
    Route::resource('grupo','grupoController');
    Route::resource('practicas','practicasController');
    Route::get('practicas/estudiantes/{id}','practicasController@estudiantes');
    Route::post('practicas/estudiantes/{id}','practicasController@estudiantesStore');
    Route::get('practicas/evaluar/{id}','practicasController@evaluar');
    Route::post('practicas/evaluar/{id}','practicasController@evaluarEstudiante');
    Route::post('practicas/evaluar/{id}/{estudiante}','practicasController@evaluarStore');
    Route::resource('inscripcion','InscripcionEstudianteCursoController');
    Route::resource('periodo','periodoController');
    Route::resource('rotacion','rotacionController');
    Route::resource('homologacion','homologacionController');
    Route::get('ajax/cargarRotaciones','ajaxController@cargarRotaciones');
    Route::get('graficas','graficasController@index');
    Route::get('graficar','graficasController@graficar');
});

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

app/TipoEvento.php
<?php

namespace FCS;

use Illuminate\Database\Eloquent\Model;

class TipoEvento extends Model
{
    protected $table = 'tipo_eventos';
    protected $fillable=['nombre_tipoevento'];

    public static function allLists()
    {
        return self::get()->lists('nombre_tipoevento' ,'id' );
    }

   
}

app/Http/Controllers/TipoEventoController.php
<?php

namespace FCS\Http\Controllers;

use Illuminate\Http\Request;
use FCS\TipoEvento;
use FCS\Http\Requests;
use Session;
use Redirect;
use FCS\Http\Requests\TipoEvento\CreateRequest;
use FCS\Http\Controllers\Controller;

class TipoEventoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");

        $tipo_eventos=TipoEvento::All();
        return view('componentes.tipo_evento.index',compact('tipo_eventos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");
        return view('componentes.tipo_evento.addtipoevento');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(CreateRequest $request)
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");

        TipoEvento::create($request->all());
        return redirect('tipo-evento')->with('message','Tipo Evento creado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");

        $tipo_eventos=TipoEvento::find($id);
        $route = [ 'route'=>['tipo-evento.update',$tipo_eventos->id],'method'=>'PUT'];
        return view('componentes.tipo_evento.edittipoevento',compact('route','tipo_eventos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(CreateRequest $request, $id)
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");

        $tipo_eventos=TipoEvento::find($id);
        $tipo_eventos->fill($request->all());
        $tipo_eventos->save();

        Session::flash('message','Tipo Evento Editado Correctamente');
        return redirect::to('tipo-evento');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        if(!\FCS\Permiso::verificarPermiso("tipo-evento"))
        return redirect("/");
    
        TipoEvento::destroy($id);
        Session::flash('message','Tipo Evento Eliminado Correctamente');
        return Redirect::to('/tipo-evento');
    }
}

resources/views/componentes/tipo_evento/addtipoevento.blade.php
@extends('layaouts.tablas')

@section('content')
  <section class="content">
    <div class="row">
      <div class="col-md-9">
      @include('errors.partials.requesterror')
        <div class="box box-solid box-danger">
          <div class="box-header with-border">
            <h3 class="box-title">Agregar Tipo Evento</h3>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="pad">
                {!!Form::open(['route'=>'tipo-evento.store','method'=>'POST'])!!}
                @include('componentes.tipo_evento.partials.form')  
                {!! Form::submit('Guardar',['class'=>'btn btn-primary']) !!}
                {!!Form::close()!!}    
              </div>
            </div><!-- /.row pad-->
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>
  </section><!-- /.content -->
@endsection

resources/views/componentes/tipo_evento/edittipoevento.blade.php
@extends('layaouts.tablas')

@section('content')
  <section class="content">
    <div class="row">
      <div class="col-md-9">
      @include('errors.partials.requesterror')
        <div class="box box-solid box-danger">
          <div class="box-header with-border">
            <h3 class="box-title">Editar Tipo Evento</h3>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="pad">
                {!!Form::model($tipo_eventos,$route)!!}
                @include('componentes.tipo_evento.partials.form')
                {!! Form::submit('Actualizar',['class'=>'btn btn-primary']) !!}
                {!!Form::close()!!}    
              </div>
            </div><!-- /.row pad-->
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>
  </section><!-- /.content -->
@endsection

resources/views/componentes/tipo_evento/index.blade.php
@extends('layaouts.tablas')
@section('content')
  <section class="content">
    @include('componentes.tipo_evento.partials.modal')  
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            @include('layaouts.partials.mensaje')
            <h3 class="box-title">Listado Tipo Eventos</h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <div class="row form-group">
              <div class="col-md-3">
                <a href="{!! URL('tipo-evento/create') !!}" class="btn btn-success"><i class="fa fa-plus"></i> Nuevo Tipo De Evento</a>
              </div>
            </div>
            <table id="example3" class="table table-bordered table-striped">
              <thead>
                <th>Tipo Evento</th>
                <th>Acción</th>
              </thead>
              <tbody>
                @foreach($tipo_eventos as $tevento)
                  <tr>     
                    <td>{{ $tevento->nombre_tipoevento}}</td>
                    <td>
                      {!! link_to_route('tipo-evento.edit', $title='Editar', $parameters=$tevento->id, $atrributes=['class'=>'btn btn-warning']) !!}
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>   
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div><!-- /.col -->
    </div>                  
  </section><!-- /.content --> 
@endsection